<script setup lang="ts">
useHead({title:'Auditoría · JARVIS'})
type Entry={id:number;user_name:string|null;action:string;subject_id:string;details:string|Record<string,unknown>|null;created_at:string}
const page=ref(1)
const {data,error,pending,refresh}=await useFetch<{data:Entry[];current_page:number;last_page:number;total:number}>('/api/backend/audit',{query:{page}})
const actions:Record<string,string>={'auth.login':'Inicio de sesión','auth.logout':'Cierre de sesión','client.created':'Cliente creado','sites.created':'Sede creada','contacts.created':'Contacto creado','catalog.created':'Ítem creado','catalog.active_changed':'Estado del catálogo actualizado','price.published':'Precio publicado','rule.configured':'Regla configurada','user.created':'Usuario creado','user.access_changed':'Acceso de usuario actualizado','quote.created':'Borrador creado','quote.revised':'Revisión creada','company.published':'Empresa emisora publicada','clause.created':'Cláusula creada','clause.version_published':'Versión de cláusula publicada','clause.updated':'Cláusula actualizada','client.tax_profile_changed':'Indicador fiscal del cliente actualizado'}
function details(value:Entry['details']){if(!value)return 'Sin detalles adicionales';try{return JSON.stringify(typeof value==='string'?JSON.parse(value):value,null,2)}catch{return String(value)}}
function timestamp(value:string){return new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Bogota'}).format(new Date(value))}
</script>
<template><AdminShell title="Auditoría" description="Consulta los cambios registrados y quién los realizó."><div v-if="error" class="admin-error" role="alert">No pudimos cargar la auditoría. <button class="button secondary" @click="refresh()">Reintentar</button></div><section class="admin-card" :aria-busy="pending"><div class="admin-actions"><h2>Actividad del sistema</h2><button class="button secondary" :disabled="pending" @click="refresh()">Actualizar</button></div><p class="admin-muted">{{ data?.total ?? 0 }} registros · Horario de Bogotá</p><p v-if="!data?.data.length && !error && !pending" class="admin-muted">Todavía no hay eventos registrados.</p><div class="admin-list admin-section"><article v-for="entry in data?.data" :key="entry.id" class="admin-record"><h3>{{ actions[entry.action] || entry.action }}</h3><p class="admin-muted">{{ entry.user_name || 'Sistema' }} · {{ timestamp(entry.created_at) }}</p><p class="admin-muted">Referencia: {{ entry.subject_id }}</p><details><summary>Ver detalles del evento {{ entry.id }}</summary><pre>{{ details(entry.details) }}</pre></details></article></div><nav class="pagination" aria-label="Páginas de auditoría"><button class="button secondary" :disabled="pending||page<=1" @click="page--">Anterior</button><span class="admin-muted">{{ page }} / {{ data?.last_page || 1 }}</span><button class="button secondary" :disabled="pending||page>=(data?.last_page || 1)" @click="page++">Siguiente</button></nav></section></AdminShell></template>
