<script setup lang="ts">
import { families, bps } from '#shared/admin'
import { errorMessages, cents } from '~/utils/format'
useHead({title:'Reglas comerciales · JARVIS'})
type Rule={family:keyof typeof families;minimum_margin_bps:number;max_discount_bps:number;review_above_cents:string}
const {data,error,refresh}=await useFetch<{data:Rule[]}>('/api/backend/rules')
const errors=ref<string[]>([]),success=ref(''),pending=ref(false)
const form=reactive({family:'',margin:'',discount:'',review_above:'',reason:''})
async function save(){if(pending.value)return;pending.value=true;errors.value=[];success.value='';try{const margin=bps(form.margin),discount=bps(form.discount);if(!Number.isInteger(margin)||!Number.isInteger(discount)||margin>10000||discount>10000)throw {data:{message:'Ingresa porcentajes entre 0 y 100, con hasta dos decimales.'}};await $fetch('/api/backend/rules',{method:'POST',body:{family:form.family,minimum_margin_bps:margin,max_discount_bps:discount,review_above:form.review_above.replace(',','.'),reason:form.reason}});form.reason='';success.value='Regla comercial guardada.';await refresh()}catch(e){errors.value=errorMessages(e)}finally{pending.value=false}}
function edit(rule:Rule){const amount=BigInt(rule.review_above_cents);Object.assign(form,{family:rule.family,margin:String(rule.minimum_margin_bps/100),discount:String(rule.max_discount_bps/100),review_above:`${amount/100n}.${String(amount%100n).padStart(2,'0')}`,reason:''})}
</script>
<template><AdminShell title="Reglas comerciales" description="Define los límites aprobados por tu empresa para cada familia." :errors="errors" :success="success"><div v-if="error" class="admin-error" role="alert">No pudimos cargar las reglas. <button class="button secondary" @click="refresh()">Reintentar</button></div><div class="admin-grid"><section class="admin-card"><h2>Configurar una familia</h2><form class="admin-form" @submit.prevent="save"><label>Familia<select v-model="form.family" required><option value="">Seleccionar…</option><option v-for="(label,key) in families" :key="key" :value="key">{{ label }}</option></select></label><label>Margen mínimo (%)<input v-model="form.margin" required inputmode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?"></label><label>Descuento máximo (%)<input v-model="form.discount" required inputmode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?"></label><label>Revisión por monto superior a (COP)<input v-model="form.review_above" required inputmode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?"></label><label>Motivo<textarea v-model="form.reason" required minlength="5" maxlength="1000" /></label><p class="admin-muted">Usa los valores autorizados por la empresa. Guardar reemplaza la configuración de esta familia y registra el cambio en auditoría.</p><button class="button primary" :disabled="pending">Guardar regla</button></form></section><section class="admin-card"><h2>Configuración actual</h2><p v-if="!data?.data.length && !error" class="admin-muted">Aún no hay reglas configuradas.</p><div class="admin-list"><article v-for="rule in data?.data" :key="rule.family" class="admin-record"><h3>{{ families[rule.family] }}</h3><p class="admin-muted">Margen mínimo: {{ rule.minimum_margin_bps/100 }} % · Descuento máximo: {{ rule.max_discount_bps/100 }} %</p><p class="admin-muted">Revisión por encima de {{ cents(rule.review_above_cents) }}</p><button class="button secondary" :disabled="pending" @click="edit(rule)">Editar {{ families[rule.family] }}</button></article></div></section></div></AdminShell></template>
