<script setup lang="ts">
import { roles } from '#shared/admin'
import { errorMessages } from '~/utils/format'
useHead({title:'Usuarios · JARVIS'})
type User={id:number;name:string;email:string;role:keyof typeof roles;active:boolean}
const {user:session}=useAuth()
const {data,error,refresh}=await useFetch<{data:User[]}>('/api/backend/users')
const errors=ref<string[]>([]),success=ref(''),pending=ref(false)
const form=reactive({name:'',email:'',password:'',role:''})
const edits=reactive<Record<number,{role:keyof typeof roles;active:boolean}>>({})
watch(data,()=>{for(const u of data.value?.data??[])edits[u.id]={role:u.role,active:u.active}},{immediate:true})
async function create(){if(pending.value)return;pending.value=true;errors.value=[];success.value='';try{await $fetch('/api/backend/users',{method:'POST',body:form});Object.assign(form,{name:'',email:'',password:'',role:''});success.value='Usuario creado.';await refresh()}catch(e){errors.value=errorMessages(e)}finally{pending.value=false}}
async function update(id:number){if(pending.value)return;pending.value=true;errors.value=[];success.value='';try{await $fetch(`/api/backend/users/${id}`,{method:'PATCH',body:edits[id]});success.value='Acceso actualizado. Las sesiones anteriores de ese usuario se cerraron.';await refresh()}catch(e){errors.value=errorMessages(e)}finally{pending.value=false}}
</script>
<template><AdminShell title="Usuarios y permisos" description="Administra quién puede cotizar, aprobar y configurar el sistema." :errors="errors" :success="success"><div v-if="error" class="admin-error" role="alert">No pudimos cargar los usuarios. <button class="button secondary" @click="refresh()">Reintentar</button></div><div class="admin-grid"><section class="admin-card"><h2>Crear usuario</h2><form class="admin-form" @submit.prevent="create"><label>Nombre<input v-model="form.name" required maxlength="255" autocomplete="name"></label><label>Correo electrónico<input v-model="form.email" type="email" required maxlength="255" autocomplete="off"></label><label>Contraseña inicial<input v-model="form.password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><p class="admin-muted">Mínimo 12 caracteres.</p><label>Rol<select v-model="form.role" required><option value="">Seleccionar…</option><option v-for="(label,key) in roles" :key="key" :value="key">{{ label }}</option></select></label><button class="button primary" :disabled="pending">Crear usuario</button></form></section><section class="admin-card"><h2>Accesos actuales</h2><div class="admin-list"><article v-for="u in data?.data" :key="u.id" class="admin-record"><h3>{{ u.name }}</h3><p class="admin-muted">{{ u.email }}</p><p v-if="u.id===session?.id" class="admin-muted">Tu cuenta · {{ roles[u.role] }}. No puedes cambiar tu propio acceso.</p><form v-else-if="edits[u.id]" class="admin-form" @submit.prevent="update(u.id)"><label>Rol de {{ u.name }}<select v-model="edits[u.id]!.role"><option v-for="(label,key) in roles" :key="key" :value="key">{{ label }}</option></select></label><label class="admin-check"><input v-model="edits[u.id]!.active" type="checkbox">Cuenta activa</label><button class="button secondary" :disabled="pending || (edits[u.id]!.role===u.role && edits[u.id]!.active===u.active)">Guardar acceso de {{ u.name }}</button></form></article></div></section></div></AdminShell></template>
